python train.py \
--niter 15 \
--niter_decay 15 \
--display_port 8091 \
--batchSize 10 \
--gpu_ids 0,1 \
--name depth_commutative_synthia-cityscapes_512x304 \
--model commutative \
--img_source_file /media/hpc-4_Raid/dsungatullina/transfer-to-zhores/_lists_512/synthia_rgb_train.txt \
--img_target_file /media/hpc-4_Raid/dsungatullina/transfer-to-zhores/_lists_512/cityscapes_rgb_train.txt \
--lab_source_file /media/hpc-4_Raid/dsungatullina/transfer-to-zhores/_lists_512/synthia_depth_train.txt \
--lab_target_file /media/hpc-4_Raid/dsungatullina/transfer-to-zhores/_lists_512/cityscapes_depth_train.txt \
--shuffle \
--crop \
--cropSize 256 \
--flip \
--rotation \
--init_models \
--init_depth_netG_filename /media/hpc-4_Raid/dsungatullina/submission/pytorch-commutative/init_models/latest_net_img2task.pth \
--init_syn2real_netG_filename /media/hpc-4_Raid/dsungatullina/submission/pytorch-commutative/init_models/5_net_G_B.pth \
--init_syn2real_netD_filename /media/hpc-4_Raid/dsungatullina/submission/pytorch-commutative/init_models/5_net_D_B.pth \
--init_real2syn_netG_filename /media/hpc-4_Raid/dsungatullina/submission/pytorch-commutative/init_models/5_net_G_A.pth \
--init_real2syn_netD_filename /media/hpc-4_Raid/dsungatullina/submission/pytorch-commutative/init_models/5_net_D_A.pth\

