python train.py \
--continue_train \
--niter 10 \
--niter_decay 10 \
--display_port 8090 \
--batchSize 4 \
--gpu_ids 0,1 \
--name synthia_supervised_1024x608_floatdepth_normalized \
--model supervised \
--shuffle \
--img_source_file /media/hpc-4_Raid/dsungatullina/transfer-to-zhores/_lists_1024/synthia_rgb_train.txt \
--img_target_file /media/hpc-4_Raid/dsungatullina/transfer-to-zhores/_lists_1024/synthia_rgb_val.txt \
--lab_source_file /media/hpc-4_Raid/dsungatullina/transfer-to-zhores/_lists_1024/synthia_depth_train.txt \
--lab_target_file /media/hpc-4_Raid/dsungatullina/transfer-to-zhores/_lists_1024/synthia_depth_val.txt  \
--crop \
--cropSize 512 \
--flip \
--rotation \
